---
title: "Estrutura do Livro"
author: "Vinicius Melquíades de Sousa"
output: 
  html_document:
    number_sections: true
date: "`r Sys.Date()`"
---

# Prefácio {-} 

1. Motivação
    - Para quem é este livro?
    - O que você vai aprender (que no inicio pode ser )
2. Estrutura 
    - convenções de notação
    - do livro
    - de cada capítulo
3. Sobre o autor
4. Agradecimentos


#  Parte I: Introdução ao mundo R {-}

# R e Rstudio

- o que são
- layout dp RStudio
- scripts
- Funcionamento do codigo
- working direcory
- pacotes (lembrar de falar pra baixar do github e cran)

# Primeiros comandos no R

- Calculadora
- Workspace/Environment
- Funções
- Ajuda e documentação (aqui falar sobre erros, mensagens e avisos)

# Estruturas de dados

- Tipos de dados, i.e., "modes"
- Vetores
- Matrizes
- *Data frames*
- Listas


# Parte II: Dados {-}

# Importar dados para o R

- Importar dados locais
    - read.csv()
    - read.stata()
    - read.spss() 
- Importar dados (de economia) direto do R 
    - Economia brasileira: BETS, rbcb, ribge, ecoseries
    - Economia Geral: Quandl, quantmod etc...

# Tidy Data (pacotes dplyr and tidyr)
- Digressão introduzindo os tibbles
- Modificando um mesmo dataset
    - long to wide
    - wide to long
- Juntando data sets diferentes
- filter, group_by, mutate()

# Salvar dados

- Salvar como csv
- Salvar como .RDATA

# Parte III: Análise de dados {-}

# Plots
- Histograma
- Scatter-plot
- Plotar densidade de variáveis
- boxplot

# Teste de hipótese (baseado na mat?ria advanced data analysis)

- Intervalo de confiança
- Independent t-test/wilcox rank sum
- Paired t-test/wilcox signed-rank test
- chi square test

# Análise de regressão

Assunto de econometria I

# Séries temporais

Assunto de econometria II
    
- Plot de series temporais

# modelos em painel

Assunto de econometria III

#   Parte IV: topicos avancados {-}

# Estruturas de programacao

- se, então (IF -ELSE)
- *for loop*
- *nested loop* ( se, entao dentro de *loop*)
- exemplos de utilização: (i) loop para pegar mais de uma série temporal com o rbcb; (ii) popuar matrizes/data frames

# Escrever funcoes 


# INtroducao ao pacote ggplot2

- "Logica" do ggplot2 (*grammar of graphics*) 


# trabalhos para entregar (r markdowmn)

# boas praticas no script

- colocar no inicio da seção o setwd() e não mudar durante a seção
- comentar os passos como `ctr+alt+r`
- carregar pacotes no inicio do script
- mostrar como programar facilita quando as atividades são mais complexas e evita repetições
- ensinar a fazer trabalhos para entregar no RMarkdown

# observação importante: ver se vou deixar ou não exercícios